server:
  port: 8765
  servlet:
    context-path: /weather
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: weather-rest
  profiles:
    active: local  #加载url的配置文件
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.base.weather.entity
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true

# PageHelper 配置
pagehelper:
  helper-dialect: postgresql  # 数据库方言
  reasonable: true  # 分页参数合理化，默认false。当该参数设置为true时，pageNum<=0时会查询第一页，pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true  # 支持通过Mapper接口参数来传递分页参数
  params: count=countSql  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射
  auto-runtime-dialect: true  # 自动检测数据库方言
  auto-close: false  # 设置为false，避免自动关闭分页
  close-conn: false  # 设置为false，避免自动关闭连接
